# Uses Github Actions to Deploy on Azure 
# see https://github.com/Azure/webapps-container-deploy
#
# Prereqs: 
# - Create Service Principal for RBAC
# az ad sp create-for-rbac --name "${WEBAPP_NAME}" --role contributor \
#                             --scopes /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RESOURCE_GROUP} \
#                             --sdk-auth
#    Add this as a AZURE_CREDENTIALS secret in Github 
# - Azure Container Registry
#   doctorathome.azurecr.io

on: 
  push:
    branches:
    - master

name: doctor_at_home_bff

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo, master branch
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
      with:
        ref: master

    # login to Azure 
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # login to Azure container registry
    - uses: azure/docker-login@v1
      with:
        login-server: doctorathome.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t doctorathome.azurecr.io/doctor-at-home-bff:latest
        docker push doctorathome.azurecr.io/doctor-at-home-bff:latest
      
    - uses: azure/webapps-container-deploy@v1
      with:
        app-name: 'doctor-at-home-bff'
        images: 'doctorathome.azurecr.io/doctor-at-home-bff:latest'
    
    - name: Azure logout
      run: |
        az logout
